//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapikuldeep.connect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class kuldeepEntities : DbContext
    {
        public kuldeepEntities()
            : base("name=kuldeepEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<my_table> my_table { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
    
        public virtual ObjectResult<showdata_Result> showdata()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showdata_Result>("showdata");
        }
    }
}
